cafe/urls.py
from django.urls import path

from . import views

# URL 네임스페이스 지정
app_name = 'cafe'

# name=''는 별칭이다
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:product_id>/',views.detail, name='detail'),
    path('product/create/', views.product_create, name='product_create'),
]

common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('register/',views.register, name='register'),
    path('logout/',views.logout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cafe/',include('cafe.urls')),
    path('common/',include('common.urls')),
]

# 서버 열리자마자 http://127.0.0.1:8000/cafe/ 로 redirect
urlpatterns += [
    path('',lambda request: redirect('cafe:index'), name='root')
]

cafe/models.py
from django.db import models

# Create your models here.

# Product에 해당하는 모델 정의
class Product(models.Model):

    # choices
    SIZE_CHOICES = [
        ('SMALL','small'),
        ('LARGE','large')
    ]
    category = models.CharField(max_length=20) # 카테고리
    #  DecimalField는 숫자를 저장하기 위한 필드 유형 중 하나이며, max_digits 매개변수는 소수점을 포함한 숫자의 최대 자릿수를, decimal_places 매개변수는 소수점 아래 자릿수를 나타냅니다.
    price = models.DecimalField(max_digits=10, decimal_places=0) # 가격
    cost = models.DecimalField(max_digits=10, decimal_places=0) # 원가
    name = models.CharField(max_length=50) #이름
    description = models.TextField() # 설명
    barcode = models.TextField() # 바코드
    exp_date = models.TextField() # 유통기한
    size = models.CharField(max_length=20,choices=SIZE_CHOICES,default='SMALL') # 사이즈
    create_date = models.DateTimeField() # 생성시기
    
    # 이름 으로 표시되게
    def __str__(self):
        return self.name

common/models.py
from django.db import models
# 유효성 검사
from django.core.validators import RegexValidator
from django.contrib.auth.hashers import make_password,check_password

# Create your models here.
# User에 해당하는 모델 정의
class User(models.Model):
    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-([0-9]{3,4})-([0-9]{4})$')
    phoneNumber = models.CharField(validators=[phoneNumberRegex],max_length=11,unique=True)
    password = models.CharField(max_length=128)
    
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    # 이름으로 표시되게
    def __str__(self):
        return self.phoneNumber

cafe/forms.py
from django import forms
from cafe.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product # 사용할 모델
        fields = ['category','price','cost','name','description','barcode',
                  'exp_date','size']

common/forms.py
from django import forms
from .models import User

# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['phoneNumber', 'password']
#         widgets = {
#             'phoneNumber': forms.TextInput(attrs={'placeholder': '휴대폰번호를 입력하세요'}),
#             'password': forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력하세요'}),
#         }

class LoginForm(forms.Form):
    phoneNumber = forms.CharField(max_length=11, required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

    def clean(self):
        cleaned_data = super().clean()
        phoneNumber = cleaned_data.get('phoneNumber')
        password = cleaned_data.get('password')

        try:
            user = User.objects.get(phoneNumber=phoneNumber)
        except User.DoesNotExist:
            raise forms.ValidationError('등록된 사용자가 없습니다.')
        
        if not user.check_password(password):
            raise forms.ValidationError('비밀번호가 틀립니다.')

        return cleaned_data

cafe/views.py
from datetime import datetime
from django.shortcuts import redirect, render, get_object_or_404
from .models import Product
from .forms import ProductForm
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    page = request.GET.get('page','1') # 페이지
    product_list = Product.objects.order_by('-create_date')
    paginator = Paginator(product_list,10) # 페이지당 10개씩
    page_obj = paginator.get_page(page)
    context = {'product_list': page_obj}
    return render(request, 'cafe/product_list.html', context) 

# 상세조회
def detail(request,product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {'product':product}
    return render(request, 'cafe/product_detail.html',context)

def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.create_date= datetime.now()
            product.save()
            return redirect('cafe:index')
    else:
        form = ProductForm()
    context={'form':form}
    return render(request, 'cafe/product_form.html', context)

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password,check_password
from django.contrib import messages
from .models import User
from .forms import LoginForm





# Create your views here.
# 로그인
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phoneNumber']
            raw_password = form.cleaned_data['password']
            try:
                user = User.objects.get(phoneNumber=phone_number)
            except User.DoesNotExist:
                user = None
                messages.warning(request, '등록된 사용자가 없습니다.')
                return render(request, 'common/login.html', {'form': form})
            if user.check_password(raw_password):
                request.session['user_phoneNumber']=user.phoneNumber
                return redirect('cafe:index')
            else:
                messages.warning(request, '비밀번호가 틀립니다.')
                return render(request, 'common/login.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'common/login.html', {'form': form})
            


# 회원가입
def register(request):
    if request.method == 'POST':
        phone_number = request.POST.get('phone_number')
        raw_password = request.POST.get('password')
        password = make_password(raw_password)

        # 중복된 휴대폰 번호 검사
        if User.objects.filter(phoneNumber=phone_number).exists():
            messages.warning(request, '이미 가입된 휴대폰번호입니다.')
            return redirect('common:register')

        # User 모델의 객체 생성
        user = User(phoneNumber=phone_number, password=password)
        user.save()

        return redirect('cafe:index')
    
    else:
        
        return render(request, 'common/register.html')

def logout(request):
    if 'user_phoneNumber' in request.session:
        
        del request.session['user_phoneNumber']
    return redirect('common:login')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap.min.css' %}"
    />
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>My Cafe</title>
  </head>
  <body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
  </body>
</html>

templates/cafe/product_detail.html
{% extends 'base.html'%} {% block content %}
<!-- 상품 상세 내역 -->
<!-- 상품 속성 -->
<!-- 카테고리,가격,원가,이름,설명,바코드,유통기한,사이즈,생성시기-->
<h3>카테고리: {{product.category}}</h3>
<h3>이름: {{product.name}}</h3>
<h3>가격: {{product.price}}</h3>
<h3>원가: {{product.cost}}</h3>
<h3>설명: {{product.description}}</h3>
<h3>바코드: {{product.barcode}}</h3>
<h3>유통기한: {{product.exp_date}}</h3>
<h3>사이즈: {{product.size}}</h3>
<h3>등록일자: {{product.create_date}}</h3>

{%endblock%}

templates/cafe/product_form.html
{% extends 'base.html'%} {%block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">상품등록</h5>
  <form method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/cafe/product_list.html
<!-- 부트스트랩 적용 -->
{% extends 'base.html'%}
{% block content %}

<div class="container my-3">
  <h1>Cafe의 메뉴입니다</h1>
  {% if product_list %}
  {% for product in product_list %}
  <div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">이름: {{product.name}}</h5>
      <p class="card-text">카테고리 :{{product.category}}</p>
      <p class="card-text">가격: {{product.price}}원</p>
      <p class="card-text">설명: {{product.description}}</p>
      <p class="card-text">사이즈: {{product.size}}</p>
      <a href="{% url 'cafe:detail' product.id %}" class="btn btn-primary">자세히</a>
    </div>
  </div>
  {% endfor %}
{% else %}
    <h4>상품이 없습니다</h3>
{%endif%}
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
  <!-- 이전페이지 -->
  {% if product_list.has_previous %}
  <li class="page-item">
      <a class="page-link" href="?page={{ product_list.previous_page_number }}">이전</a>
  </li>
  {% else %}
  <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
  </li>
  {% endif %}
  <!-- 페이지리스트 -->
  {% for page_number in product_list.paginator.page_range %}
  {% if page_number >= product_list.number|add:-5 and page_number <= product_list.number|add:5 %}
  {% if page_number == product_list.number %}
  <li class="page-item active" aria-current="page">
      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% else %}
  <li class="page-item">
      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% endif %}
  {% endif %}
  {% endfor %}
  <!-- 다음페이지 -->
  {% if question_list.has_next %}
  <li class="page-item">
      <a class="page-link" href="?page={{ product_list.next_page_number }}">다음</a>
  </li>
  {% else %}
  <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
  </li>
  {% endif %}
</ul>
<!-- 페이징처리 끝 -->
<a href="{% url 'cafe:product_create' %}" class="btn btn-primary">상품 등록하기</a>
</div>
{% endblock %}

templates/common/login.html
{% extends 'base.html'%} {%block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">로그인</h5>
  <form method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="btn btn-primary">로그인하기</button>
  </form>
</div>
{% endblock %}

templates/common/register.html
{% extends "base.html" %} 
{% block content %}
<form method="POST">
  {% csrf_token %}
  <label>전화번호 입력</label>
  <input type="text" name="phone_number" maxlength="11" required />
  <br />
  <label>비밀번호 입력</label>
  <input type="password" name="password" required />
  <br />
  <input type="submit" value="회원가입" />
</form>

<!-- 에러메시지 출력 -->
{% for message in messages %}
    {{ message.tag }}
    {{ message }}
{% endfor %}

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'cafe:index' %}">Cafe</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item d-flex justify-content-around">
          {% if request.session.user_phoneNumber %}
          <a class="nav-link" href="{% url 'common:logout' %}"
            >{{request.session.user_phoneNumber}}(로그아웃)</a
          >
          {% else %}
          <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
          <a class="nav-link" href="{% url 'common:register' %}">회원가입</a>
        </li>
      </ul>
    </div>
  </div>
</nav>